package testing;

/**
 * The Tester3 class is used to demonstrate the functionality of the Plotter3, Salter3, and Smoother3 classes.
 * It creates instances of these classes and invokes their respective methods to display their graphical output.
 * 
 *  * @author Hope Lepeshko
 */
public class Tester3 {
    
    /**
     * The main method serves as the entry point for the program.
     * It creates instances of Plotter3, Salter3, and Smoother3, and displays their charts.
     * 
     * @param args Command line arguments 
     */
    public static void main(String[] args) {

        // Testing Plotter3
        Plotter3 plotter = new Plotter3("Plotter3");
        plotter.display();  // Display the graph generated by Plotter3

        // Testing Salter3
        Salter3 salter = new Salter3("Salter3");
        salter.displayChart();  // Assuming Salter3 has a method to display the chart

        // Testing Smoother3
        Smoother3 smoother = new Smoother3("Smoother3");
        smoother.displayChart();  // Display the chart generated by Smoother3
    }
    
    /**
    * Used Chat GPT to check work and find mistakes
    * 
    */
}
